<a href="https://colab.research.google.com/github/shamitha2310/python-mini-project/blob/main/Introduction_to_numpyS2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Recap
arr = np.array([[1,2,3,],[4,5,6]])

In [3]:
type(arr)

numpy.ndarray

In [24]:
# Dot product - m x n || n x p
arr1 = np.random.randint(1,2,(1,2))

In [25]:
arr.shape
arr1.shape

(1, 2)

In [10]:
result = np.dot (arr,arr1)

In [11]:
print(result)

[[ 6]
 [15]]


In [13]:
r1 = np.random.randint(10,20,(3,3))
print (r1)

[[19 16 13]
 [11 18 11]
 [10 13 11]]


In [15]:
r2 = np.eye(3)
print (r2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# r1.I
result2 = np.dot(r1,r2)

In [17]:
print(result2)

[[19. 16. 13.]
 [11. 18. 11.]
 [10. 13. 11.]]


In [18]:
# mathematical operations
# + - * /
t1 = np.random.randint(3,6,(3,3))
t2 = np.random.randint(3,6,(3,3))

In [19]:
print(t1)
print(t2)

[[3 4 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [4 3 5]
 [5 4 3]]


In [21]:
t3 = t1*t2
print(t3)

[[ 9 16 15]
 [12  9 20]
 [25 12 15]]


In [26]:
# Matrix multiplication
result = np.dot(arr1,arr)

In [33]:
# Statistical operations
mean = t3.mean()
max = t3.max()
median=np.median(t3)
std = np.std(t3)
var = np.var(t3)

In [34]:
print(max)

25


In [35]:
print(median)

15.0


In [36]:
print(var)

23.950617283950617


In [37]:
print(std)

4.893936787898943


In [38]:
std*std

23.95061728395062

In [51]:
# Trigonometry functions

#sin(x)
#cos(x)
#Tan(x) - sin(x) / cos(x)
#cosec - 1 / sin(x)
#sec - 1 / cos(x)
#cot - /tan(x)
#
angles = np.array([0,15,30,45,60,75,90])

#sin(array)

result= np.sin(np.radians(angles))
result1 = np.cos(np.radians(angles))
result2 = np.tan(np.radians(angles))

In [52]:
print(result)
print(result1)
print(result2)

[0.         0.25881905 0.5        0.70710678 0.8660254  0.96592583
 1.        ]
[1.00000000e+00 9.65925826e-01 8.66025404e-01 7.07106781e-01
 5.00000000e-01 2.58819045e-01 6.12323400e-17]
[0.00000000e+00 2.67949192e-01 5.77350269e-01 1.00000000e+00
 1.73205081e+00 3.73205081e+00 1.63312394e+16]


In [53]:
arr = np.array([1,2,3,4,5,6])

#reshape the array
reshapedarr=arr.reshape(2,3)
print(reshapedarr)

[[1 2 3]
 [4 5 6]]


In [54]:
#Reshape the array
reshapedarr = arr.reshape(3,2)

print (reshapedarr)

# Convert / Faltten any n dim array
flattenedarr = arr.flatten()

[[1 2]
 [3 4]
 [5 6]]


In [50]:
# stacking the data

arr1 = np.array([1,2,3,4])
arr2 = np.array([10,20,30,40])


#Vertical Stacking
arr3 = np.vstack([arr1,arr2])
print(f"The shape of arr3 is {arr3.shape}")

#Horizantal stacking
arr4 = np.hstack([arr1,arr2])
print(f"The shape of arr4 is {arr4.shape}")
print(arr4)

The shape of arr3 is (2, 4)
The shape of arr4 is (8,)
[ 1  2  3  4 10 20 30 40]


In [55]:
#Filtering
arr = np.array([10,20,30,40,50,60,70,80])

farr = arr[arr >40]
print (farr)

[50 60 70 80]
